name: shared_preferences_ios_sn
description: Simply to wrap the Flutter plugin shared_preferences plugin and provide iOS "suite name" feature
repository: https://github.com/iwantofun/shared_preferences_ios_sn
issue_tracker: https://github.com/iwantofun/shared_preferences_ios_sn/issues
version: 1.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: shared_preferences
    platforms:
      ios:
        pluginClass: FLTSharedPreferencesSNPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  shared_preferences: ^2.0.9
  shared_preferences_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
